## Tensor Factorization

In [1]:
from MF import *
import tensorly as tl
import tensorly.tenalg as ta

### Using Gradient descent algorithm

In [2]:
X = tl.eye(3)
mask = tl.ones(X.shape)

result, A = parafac_gd(X, mask=mask, penalty_weight=0)
print('\nOriginal:\n', X, '\n\nResult:\n', result)
for k, feature_map in enumerate(A):
    print(f'\nFeature {k}:\n', tl.to_numpy(feature_map))

Iterations: 6508
RMSE: 0.00867405484685836

Original:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Result:
 [[9.99293049e-01 1.68606144e-05 6.54530763e-04]
 [3.75819848e-05 9.95570432e-01 4.06952325e-03]
 [6.06958771e-04 4.00646000e-03 9.95340909e-01]]

Feature 0:
 [[ 0.03041425 -0.04423782  0.9982786 ]
 [ 0.96697875  0.24845453 -0.01875736]
 [-0.24168973  0.96879518  0.05210965]]

Feature 1:
 [[ 0.03104191 -0.0453132   0.99806244]
 [ 0.96597217  0.24611641 -0.01850666]
 [-0.24253769  0.96416291  0.050771  ]]


In [3]:
X = tl.eye(3)
mask = tl.ones(X.shape)

result, A = parafac_gd(X, mask=mask, penalty_weight=1e-6)
print('\nOriginal:\n', X, '\n\nResult:\n', result)
for k, feature_map in enumerate(A):
    print(f'\nFeature {k}:\n', tl.to_numpy(feature_map))

Iterations: 6991
RMSE: 0.008688488471761228

Original:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Result:
 [[ 9.99563542e-01 -6.95300515e-04  1.34295176e-03]
 [-6.77872637e-04  9.97336683e-01  3.82882937e-03]
 [ 1.27330573e-03  3.72762531e-03  9.94060036e-01]]

Feature 0:
 [[ 0.48120158  0.81710808 -0.31394927]
 [-0.44290664  0.5359868   0.71704223]
 [ 0.75397534 -0.20078631  0.62398476]]

Feature 1:
 [[ 0.48103902  0.81867939 -0.31577477]
 [-0.44460387  0.53594982  0.71565749]
 [ 0.75106876 -0.20227287  0.62046242]]


In [4]:
X = tl.tensor([[1, 2, 3], [2, 0, 6], [3, 6, 0]], dtype=tl.float64)
mask = tl.tensor([[1, 1, 1], [1, 0, 1], [1, 1, 0]], dtype=tl.float64)
rank = 1

result, A = parafac_gd(X, mask=mask, rank=rank, penalty_weight=1e-3, n_iter_max=100000)
print('\nOriginal:\n', X, '\n\nResult:\n', result)
for k, feature_map in enumerate(A):
    print(f'\nFeature {k}:\n', tl.to_numpy(feature_map))

Iterations: 3906
RMSE: 0.03969007158077993

Original:
 [[1. 2. 3.]
 [2. 0. 6.]
 [3. 6. 0.]] 

Result:
 [[1.00605938 2.02201754 2.98351586]
 [2.02201482 4.06392457 5.99637894]
 [2.98352552 5.99640643 8.84778362]]

Feature 0:
 [[1.00193005]
 [2.01371554]
 [2.97127975]]

Feature 1:
 [[1.00412138]
 [2.01812247]
 [2.97776862]]


In [5]:
X = tl.tensor([[1, 2, 3], [2, 0, 6], [3, 6, 0], [0, 0, 0]], dtype=tl.float64)
mask = tl.tensor([[1, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0]], dtype=tl.float64)
rank = 1

result, A = parafac_gd(X, mask=mask, rank=rank, penalty_weight=1e-3, n_iter_max=100000)
print('\nOriginal:\n', X, '\n\nResult:\n', result)
for k, feature_map in enumerate(A):
    print(f'\nFeature {k}:\n', tl.to_numpy(feature_map))

Iterations: 3917
RMSE: 0.039676603904092715

Original:
 [[1. 2. 3.]
 [2. 0. 6.]
 [3. 6. 0.]
 [0. 0. 0.]] 

Result:
 [[1.00605737e+00 2.02200957e+00 2.98352296e+00]
 [2.02200774e+00 4.06390244e+00 5.99638422e+00]
 [2.98352959e+00 5.99640296e+00 8.84783447e+00]
 [3.31263360e-03 6.65784779e-03 9.82381196e-03]]

Feature 0:
 [[1.00227756]
 [2.01441096]
 [2.97232033]
 [0.00330019]]

Feature 1:
 [[1.00377122]
 [2.01741478]
 [2.97674324]]


In [ ]:
X = tl.tensor(np.array([[0,90,449,517], [0,0,412,0], [192,0,697,687], [185,0,699,657], [164,58,0,0]]), dtype=tl.float64)
mask = tl.tensor(np.array([[0,1,1,1], [0,0,1,0], [1,0,1,1], [1,0,1,1], [1,1,0,0]]), dtype=tl.float64)
rank = 4

result, A = parafac_gd(X, mask=mask, rank=rank, penalty_weight=1e-3, n_iter_max=50000)
print('\nOriginal:\n', X, '\n\nResult:\n', result)
for k, feature_map in enumerate(A):
    print(f'\nFeature {k}:\n', tl.to_numpy(feature_map))

### Using Alternating Least Squares method

In [7]:
X = tl.eye(3)
mask = tl.ones(X.shape)
rank = 3

result, A = parafac_als(X, mask=mask, rank=rank, penalty_weight=1e-3)
print('\nOriginal:\n', X, '\n\nResult:\n', result)
for k, feature_map in enumerate(A):
    print(f'\nFeature {k}:\n', tl.to_numpy(feature_map))

Iterations: 2
RMSE: 3.638599687738519e-05

Original:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Result:
 [[ 9.99983420e-01 -1.26264740e-05 -5.68159776e-06]
 [-1.26264740e-05  9.99978145e-01 -6.89417206e-06]
 [-5.68159776e-06 -6.89417206e-06  9.99990359e-01]]

Feature 0:
 [[-4.13761265  9.41313808  2.57913021]
 [ 3.84881468 -6.01312302  6.07332273]
 [ 8.76954652  3.13397227 -7.28122317]]

Feature 1:
 [[ 0.02982157  0.09794853  0.0780769 ]
 [ 0.0923293   0.00904698  0.11509686]
 [ 0.08757747  0.04224226 -0.01367759]]


In [8]:
X = tl.tensor([[1, 2, 3], [2, 4, 6], [3, 6, 9]], dtype=tl.float64)
mask = tl.tensor([[1, 1, 1], [1, 0, 1], [1, 1, 0]], dtype=tl.float64)
rank = 1

result, A = parafac_als(X, mask=mask, rank=rank, penalty_weight=1e-3)
print('\nOriginal:\n', X, '\n\nResult:\n', result)
for k, feature_map in enumerate(A):
    print(f'\nFeature {k}:\n', tl.to_numpy(feature_map))

Iterations: 320
RMSE: 0.011390039491683376

Original:
 [[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]] 

Result:
 [[1.00229779 2.00710289 2.99800299]
 [2.00621889 4.01745646 6.00086149]
 [2.99503482 5.99756191 8.95853849]]

Feature 0:
 [[3.31604061]
 [6.63745182]
 [9.90888854]]

Feature 1:
 [[0.30225739]
 [0.6052709 ]
 [0.90409116]]


In [9]:
X = tl.tensor([[1, 2, 3], [2, 0, 6], [3, 6, 0], [0, 0, 0]], dtype=tl.float64)
mask = tl.tensor([[1, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0]], dtype=tl.float64)
rank = 1

result, A = parafac_als(X, mask=mask, rank=rank, penalty_weight=1e-3)
print('\nOriginal:\n', X, '\n\nResult:\n', result)
for k, feature_map in enumerate(A):
    print(f'\nFeature {k}:\n', tl.to_numpy(feature_map))

Iterations: 321
RMSE: 0.01138877014943058

Original:
 [[1. 2. 3.]
 [2. 0. 6.]
 [3. 6. 0.]
 [0. 0. 0.]] 

Result:
 [[1.00229753 2.0071021  2.9980032 ]
 [2.00621819 4.0174545  6.00086137]
 [2.99503537 5.99756217 8.95854306]
 [0.         0.         0.        ]]

Feature 0:
 [[3.31585242]
 [6.63707453]
 [9.90833054]
 [0.        ]]

Feature 1:
 [[0.30227447]
 [0.60530502]
 [0.90414253]]


In [10]:
X = tl.tensor(np.array([[0,90,449,517], [0,0,412,0], [192,0,697,687], [185,0,699,657], [164,58,0,0]]), dtype=tl.float64)
mask = tl.tensor(np.array([[0,1,1,1], [0,0,1,0], [1,0,1,1], [1,0,1,1], [1,1,0,0]]), dtype=tl.float64)
rank = 2

result, A = parafac_als(X, mask=mask, rank=rank, penalty_weight=1e-3)
print('\nOriginal:\n', X, '\n\nResult:\n', result)
for k, feature_map in enumerate(A):
    print(f'\nFeature {k}:\n', tl.to_numpy(feature_map))

Iterations: 2717
RMSE: 0.213734034402169

Original:
 [[  0.  90. 449. 517.]
 [  0.   0. 412.   0.]
 [192.   0. 697. 687.]
 [185.   0. 699. 657.]
 [164.  58.   0.   0.]] 

Result:
 [[ 142.09389437   89.99999924  449.00075064  517.01164119]
 [ -93.62520641   -1.73475567  411.99987663 -436.53645337]
 [ 192.1469916   129.00847471  696.99490796  686.96295448]
 [ 184.85300287  126.42643187  699.00466016  657.02946962]
 [ 163.99344395   57.99999206  -45.83808652  673.09392839]]

Feature 0:
 [[223.22718009  56.32713299]
 [119.45089581 130.09153235]
 [335.68544332  97.38845065]
 [333.66211434 100.41617682]
 [ 45.24571474 -68.22752017]]

Feature 1:
 [[ 1.06486357 -1.69745186]
 [ 0.52913869 -0.49919349]
 [ 1.57785016  1.71820762]
 [ 4.11658156 -7.13548216]]


### Graph Regularized Alternating Least Squares (GRALS)

In [11]:
X = tl.eye(3)
mask = tl.ones(X.shape)
rank = 3

result, A = parafac_grals(X, mask=mask, rank=rank, penalty_weight=1e-3)
print('\nOriginal:\n', X, '\n\nResult:\n', result)
for k, feature_map in enumerate(A):
    print(f'\nFeature {k}:\n', tl.to_numpy(feature_map))

Iterations: 2
RMSE: 3.893268130161842e-05

Original:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Result:
 [[ 9.99984268e-01 -1.13953911e-05 -4.39780098e-08]
 [-1.13953911e-05  9.99977652e-01 -5.22132574e-06]
 [-4.39780098e-08 -5.22132574e-06  9.99978679e-01]]

Feature 0:
 [[ 8.58458238 -5.10818568  2.14189355]
 [-1.76875784  8.56699192  1.18903553]
 [-1.96102962 -3.44933906  5.98128132]]

Feature 1:
 [[ 0.11481296  0.01710922  0.0475094 ]
 [ 0.0480571   0.11523621  0.08221063]
 [-0.0506683  -0.029036    0.13382779]]


In [12]:
X = tl.tensor([[1, 2, 3], [2, 4, 6], [3, 6, 9]], dtype=tl.float64)
mask = tl.tensor([[1, 1, 1], [1, 0, 1], [1, 1, 0]], dtype=tl.float64)
rank = 1

result, A = parafac_grals(X, mask=mask, rank=rank, penalty_weight=1e-3)
print('\nOriginal:\n', X, '\n\nResult:\n', result)
for k, feature_map in enumerate(A):
    print(f'\nFeature {k}:\n', tl.to_numpy(feature_map))

Iterations: 318
RMSE: 0.011391280812611237

Original:
 [[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]] 

Result:
 [[1.00229804 2.00710367 2.99800279]
 [2.00621957 4.01745837 6.0008616 ]
 [2.99503428 5.99756166 8.95853402]]

Feature 0:
 [[3.31622464]
 [6.63782076]
 [9.90943419]]

Feature 1:
 [[0.3022407 ]
 [0.60523755]
 [0.90404092]]


In [13]:
X = tl.tensor([[1, 2, 3], [2, 0, 6], [3, 6, 0], [0, 0, 0]], dtype=tl.float64)
mask = tl.tensor([[1, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 0]], dtype=tl.float64)
rank = 1

result, A = parafac_grals(X, mask=mask, rank=rank, penalty_weight=1e-3)
print('\nOriginal:\n', X, '\n\nResult:\n', result)
for k, feature_map in enumerate(A):
    print(f'\nFeature {k}:\n', tl.to_numpy(feature_map))

Iterations: 319
RMSE: 0.01138107625499142

Original:
 [[1. 2. 3.]
 [2. 0. 6.]
 [3. 6. 0.]
 [0. 0. 0.]] 

Result:
 [[1.00229598 2.00709727 2.99800446]
 [2.00621398 4.01744266 6.00086064]
 [2.99503871 5.99756375 8.95857075]
 [0.         0.         0.        ]]

Feature 0:
 [[3.31471147]
 [6.63478718]
 [9.90494763]
 [0.        ]]

Feature 1:
 [[0.30237805]
 [0.60551191]
 [0.90445413]]


In [14]:
X = tl.tensor(np.array([[0,90,449,517], [0,0,412,0], [192,0,697,687], [185,0,699,657], [164,58,0,0]]), dtype=tl.float64)
mask = tl.tensor(np.array([[0,1,1,1], [0,0,1,0], [1,0,1,1], [1,0,1,1], [1,1,0,0]]), dtype=tl.float64)
rank = 2

result, A = parafac_grals(X, mask=mask, rank=rank, penalty_weight=1e-3)
print('\nOriginal:\n', X, '\n\nResult:\n', result)
for k, feature_map in enumerate(A):
    print(f'\nFeature {k}:\n', tl.to_numpy(feature_map))

Iterations: 10000
RMSE: 2.1059154806299487

Original:
 [[  0.  90. 449. 517.]
 [  0.   0. 412.   0.]
 [192.   0. 697. 687.]
 [185.   0. 699. 657.]
 [164.  58.   0.   0.]] 

Result:
 [[149.60117612  89.97387125 449.00548551 517.00251505]
 [-21.84064631  22.39772277 411.99103046  -1.14470979]
 [193.40483862 124.99451541 697.07556326 686.53219515]
 [183.58638424 121.41998396 698.92770238 657.47623047]
 [163.92726659  58.01831971 -53.2518618  481.63782275]]

Feature 0:
 [[  -5.68041804  150.50533955]
 [  85.16406507   63.62479549]
 [  13.24807913  215.4737874 ]
 [  19.15218601  211.21010374]
 [-102.51728982   67.1833946 ]]

Feature 1:
 [[-0.97165323  0.95732005]
 [-0.17858572  0.59107159]
 [ 2.5372798   3.07908209]
 [-2.509015    3.34041478]]
